// Code generated by goctl. DO NOT EDIT.
// Source: train_proxy.proto

package server

import (
	"context"

	"github.com/chinabobo/learning-go-zero/rpc/internal/logic"
	"github.com/chinabobo/learning-go-zero/rpc/internal/svc"
	"github.com/chinabobo/learning-go-zero/rpc/train_proxy"
)

type TrainProxySrvServer struct {
	svcCtx *svc.ServiceContext
	train_proxy.UnimplementedTrainProxySrvServer
}

func NewTrainProxySrvServer(svcCtx *svc.ServiceContext) *TrainProxySrvServer {
	return &TrainProxySrvServer{
		svcCtx: svcCtx,
	}
}

func (s *TrainProxySrvServer) CreateTask(ctx context.Context, in *train_proxy.CreateTaskReq) (*train_proxy.CreateTaskResp, error) {
	l := logic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}
