// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.19.4
// source: common/proto/train_proxy.proto

package train_proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainTaskType int32

const (
	TrainTaskType_TaskTypePlaceholder TrainTaskType = 0
	TrainTaskType_TaskTypeTrain       TrainTaskType = 1
	TrainTaskType_TaskTypeReset       TrainTaskType = 2
)

// Enum value maps for TrainTaskType.
var (
	TrainTaskType_name = map[int32]string{
		0: "TaskTypePlaceholder",
		1: "TaskTypeTrain",
		2: "TaskTypeReset",
	}
	TrainTaskType_value = map[string]int32{
		"TaskTypePlaceholder": 0,
		"TaskTypeTrain":       1,
		"TaskTypeReset":       2,
	}
)

func (x TrainTaskType) Enum() *TrainTaskType {
	p := new(TrainTaskType)
	*p = x
	return p
}

func (x TrainTaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrainTaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_train_proxy_proto_enumTypes[0].Descriptor()
}

func (TrainTaskType) Type() protoreflect.EnumType {
	return &file_common_proto_train_proxy_proto_enumTypes[0]
}

func (x TrainTaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrainTaskType.Descriptor instead.
func (TrainTaskType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_train_proxy_proto_rawDescGZIP(), []int{0}
}

type CreateTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MetaId   uint64        `protobuf:"varint,2,opt,name=meta_id,json=metaId,proto3" json:"meta_id,omitempty"`
	TaskId   uint64        `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType TrainTaskType `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3,enum=train_proxy.TrainTaskType" json:"task_type,omitempty"`
	ModelId  string        `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Params   string        `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *CreateTaskReq) Reset() {
	*x = CreateTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_train_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReq) ProtoMessage() {}

func (x *CreateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_train_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReq.ProtoReflect.Descriptor instead.
func (*CreateTaskReq) Descriptor() ([]byte, []int) {
	return file_common_proto_train_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTaskReq) GetMetaId() uint64 {
	if x != nil {
		return x.MetaId
	}
	return 0
}

func (x *CreateTaskReq) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CreateTaskReq) GetTaskType() TrainTaskType {
	if x != nil {
		return x.TaskType
	}
	return TrainTaskType_TaskTypePlaceholder
}

func (x *CreateTaskReq) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CreateTaskReq) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type CreateTaskResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Progress      uint32 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	EstimatedTime int64  `protobuf:"varint,3,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
}

func (x *CreateTaskResp) Reset() {
	*x = CreateTaskResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_train_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResp) ProtoMessage() {}

func (x *CreateTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_train_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResp.ProtoReflect.Descriptor instead.
func (*CreateTaskResp) Descriptor() ([]byte, []int) {
	return file_common_proto_train_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResp) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTaskResp) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *CreateTaskResp) GetEstimatedTime() int64 {
	if x != nil {
		return x.EstimatedTime
	}
	return 0
}

var File_common_proto_train_proxy_proto protoreflect.FileDescriptor

var file_common_proto_train_proxy_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x22, 0xc6, 0x01,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x61,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x61, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x6b, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x2a, 0x4e, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x61, 0x73, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x10, 0x01,
	0x12, 0x11, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x10, 0x02, 0x32, 0x56, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x53, 0x72, 0x76, 0x12, 0x45, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x1a, 0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x2e,
	0x2f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_train_proxy_proto_rawDescOnce sync.Once
	file_common_proto_train_proxy_proto_rawDescData = file_common_proto_train_proxy_proto_rawDesc
)

func file_common_proto_train_proxy_proto_rawDescGZIP() []byte {
	file_common_proto_train_proxy_proto_rawDescOnce.Do(func() {
		file_common_proto_train_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_train_proxy_proto_rawDescData)
	})
	return file_common_proto_train_proxy_proto_rawDescData
}

var file_common_proto_train_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_train_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_train_proxy_proto_goTypes = []interface{}{
	(TrainTaskType)(0),     // 0: train_proxy.TrainTaskType
	(*CreateTaskReq)(nil),  // 1: train_proxy.CreateTaskReq
	(*CreateTaskResp)(nil), // 2: train_proxy.CreateTaskResp
}
var file_common_proto_train_proxy_proto_depIdxs = []int32{
	0, // 0: train_proxy.CreateTaskReq.task_type:type_name -> train_proxy.TrainTaskType
	1, // 1: train_proxy.TrainProxySrv.CreateTask:input_type -> train_proxy.CreateTaskReq
	2, // 2: train_proxy.TrainProxySrv.CreateTask:output_type -> train_proxy.CreateTaskResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_train_proxy_proto_init() }
func file_common_proto_train_proxy_proto_init() {
	if File_common_proto_train_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_train_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_train_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTaskResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_train_proxy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_train_proxy_proto_goTypes,
		DependencyIndexes: file_common_proto_train_proxy_proto_depIdxs,
		EnumInfos:         file_common_proto_train_proxy_proto_enumTypes,
		MessageInfos:      file_common_proto_train_proxy_proto_msgTypes,
	}.Build()
	File_common_proto_train_proxy_proto = out.File
	file_common_proto_train_proxy_proto_rawDesc = nil
	file_common_proto_train_proxy_proto_goTypes = nil
	file_common_proto_train_proxy_proto_depIdxs = nil
}
