// Code generated by goctl. DO NOT EDIT.
// Source: train_proxy.proto

package trainproxysrv

import (
	"context"

	"github.com/chinabobo/learning-go-zero/rpc/train_proxy"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateTaskReq  = train_proxy.CreateTaskReq
	CreateTaskResp = train_proxy.CreateTaskResp

	TrainProxySrv interface {
		CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskResp, error)
	}

	defaultTrainProxySrv struct {
		cli zrpc.Client
	}
)

func NewTrainProxySrv(cli zrpc.Client) TrainProxySrv {
	return &defaultTrainProxySrv{
		cli: cli,
	}
}

func (m *defaultTrainProxySrv) CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskResp, error) {
	client := train_proxy.NewTrainProxySrvClient(m.cli.Conn())
	return client.CreateTask(ctx, in, opts...)
}
